# Generated by Django 3.1 on 2020-09-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('Quantity', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodItems',
        ),
    ]
